- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install essential packages
      apt:
        name:
          - vim
          - git
          - htop
          - firefox-esr
          - luanti
          - 0ad
        state: present

    - name: Clone/update dotfiles repo
      git:
        repo: https://github.com/mikeizbicki/dotfiles
        dest: "{{ ansible_env.HOME }}/dotfiles-temp"
        version: dotfiles
        force: yes
      become: no

    - name: Copy dotfiles to home directory
      shell: |
        cd {{ ansible_env.HOME }}
        cp -r dotfiles-temp/. .
        rm -rf dotfiles-temp
      become: no
