- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Configure git (avoid interactive prompts)
      shell: |
        git config --global user.email "ansible@localhost" || true
        git config --global user.name "Ansible" || true
      become: no
        
    - name: Install essential packages
      apt:
        name:
          - vim
          - git
          - htop
          - firefox-esr
          - luanti
          - 0ad
        state: present

    - name: Add user to sudoers
      user:
        name: user
        groups: sudo
        append: yes
      ignore_errors: yes  # In case user doesn't exist

    - name: Clone/update dotfiles repo
      git:
        repo: https://github.com/mikeizbicki/dotfiles
        dest: "{{ ansible_env.HOME }}/dotfiles-temp"
        version: dotfiles
        force: yes
      become: no

    - name: Copy dotfiles to home directory
      shell: |
        cp -r "{{ ansible_env.HOME }}/dotfiles-temp/." /home/user
        rm -rf "{{ ansible_env.HOME }}/dotfiles-temp"
      become: no

    - name: Add garage host entry
      lineinfile:
        path: /etc/hosts
        line: "192.168.4.131 garage"
        state: present
        backup: yes

